### PR TITLE
Vue tour

### PR DESCRIPTION
**Pull request by ianfabs**
Added and implemented vue-tour for the tutorial.

WARNING it appears everytime the page loads, gotta fix that

### CODE REVIEW

**Comment by ianfabs** [comment]
I wanna wait till matt's vuex code is merged, so i can check how many times the user has logged in to see if the tutorial should run

**Comment by KyloRilo** [comment]
Sounds good, I tentatively approve this until then

**Review by KyloRilo — APPROVED** [review]

**Review by mattsre — CHANGES_REQUESTED** [review]
Please integrate this with the Vuex store to only run on first login. The code that actually increments the login counter in the DB on login is in my auth-flow-improvements branch, so that would need to be merged prior. I'd suggest closing this PR and then re-opening it when the tour is fully integrated.

**Comment by ianfabs** [comment]
@RetWolf should I merge your auth-improvements branch into this one? or should I wait

**Comment by mattsre** [comment]
I would wait until auth-flow-improvements gets merged into dev, because that shouldn't be too long, and then merge dev into your branch

**Comment by ianfabs** [comment]
@RetWolf

**Review by mattsre — APPROVED** [review]

**Pull request merged**
